name: deploy
on:
  workflow_dispatch:

env:
  CI: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Deploy
        run: npm run deploy
        working-directory: ./frontend
